#!/usr/bin/env bash
# Displays Best School
# But for the 9th iteration displays best school and then hi

i=1
while [ $i -le 10 ]
do
	echo "Best Scool"

	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi

	i=$(( i + 1 ))
done